"""Built-in style presets for bilingual subtitle rendering."""

from __future__ import annotations

_DEFAULT_PRESETS = {
    "Standard": {
        "bottom_fontsize": 20,
        "bottom_color": "#FFFFFF",
        "bottom_outline_color": "#000000",
        "bottom_outline": 2,
        "bottom_shadow": 1,
        "bottom_bold": False,
        "bottom_margin_v": 20,
        "bottom_margin_h": 20,
        "bottom_spacing": 0,
        "font_bottom": "",
        "top_fontsize": 18,
        "top_color": "#FFD700",
        "top_outline_color": "#000000",
        "top_outline": 2,
        "top_shadow": 1,
        "top_bold": False,
        "top_margin_v": 20,
        "top_margin_h": 20,
        "top_spacing": 0,
        "font_top": "Noto Sans CJK KR",
        "layout": "top-bottom",
        "stacked_gap": 40,
    },
    "Cinema Dark": {
        "bottom_fontsize": 22,
        "bottom_color": "#FFFFFF",
        "bottom_outline_color": "#000000",
        "bottom_outline": 3,
        "bottom_shadow": 2,
        "bottom_bold": False,
        "bottom_margin_v": 40,
        "bottom_margin_h": 30,
        "bottom_spacing": 0,
        "font_bottom": "",
        "top_fontsize": 16,
        "top_color": "#FFD700",
        "top_outline_color": "#000000",
        "top_outline": 3,
        "top_shadow": 2,
        "top_bold": False,
        "top_margin_v": 10,
        "top_margin_h": 30,
        "top_spacing": 0,
        "font_top": "Noto Sans CJK KR",
        "layout": "top-bottom",
        "stacked_gap": 10,
    },
    "Bright": {
        "bottom_fontsize": 18,
        "bottom_color": "#FFFF00",
        "bottom_outline_color": "#0000FF",
        "bottom_outline": 1,
        "bottom_shadow": 0,
        "bottom_bold": True,
        "bottom_margin_v": 20,
        "bottom_margin_h": 15,
        "bottom_spacing": 0,
        "font_bottom": "",
        "top_fontsize": 16,
        "top_color": "#00FF00",
        "top_outline_color": "#0000FF",
        "top_outline": 1,
        "top_shadow": 0,
        "top_bold": True,
        "top_margin_v": 10,
        "top_margin_h": 15,
        "top_spacing": 0,
        "font_top": "Noto Sans CJK KR",
        "layout": "stacked",
        "stacked_gap": 12,
    },
}


def get_default_presets() -> dict:
    """Return a copy of the built-in default style presets."""
    return dict(_DEFAULT_PRESETS)
